using CompetitionAnalysis.Application.Messaging;
namespace CompetitionAnalysis.Application.Features.CompanyFeatures.ProductFeatures.Commands.CreateProductAll;
public sealed record CreateProductAllCommand : ICommand<CreateProductAllCommandResponse>;