using CompetitionAnalysis.Application.Messaging;
namespace CompetitionAnalysis.Application.Features.CompanyFeatures.ProductFeatures.Commands.CreateProductCompany;
public sealed record CreateProductCompanyCommand(string companyId) : ICommand<CreateProductCompanyCommandResponse>;